#!/bin/sh -e
#
#    powernap-now - send powernapd the 'now' signal
#
#    Copyright (C) 2010 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

PKG="powernap"
PIDFILE=/var/run/$PKG.pid

if [ -r $PIDFILE ]; then
	echo "Sending $PKG the 'now' signal"
	kill -USR1 $(cat $PIDFILE)
	exit $?
else
	echo "$PKG does not appear to be running"
	exit 1
fi
