#!/bin/sh
#
#    usb_remove_one: Removes support for USB 1.1 to save power.
#
#    Copyright (C) 2010 Canonical Ltd.
#
#    Authors: Andres Rodriguez <andreserl@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

usb_remove_one() {
	if [ $1 -eq 1 ]; then
		rmmod uhci_hcd
	else
		modprobe uhci_hcd
	fi
}

help() {
	echo "Removes support of USB 1.1 to save power."
}

case $1 in
	true)
		usb_remove_one 1 ;;
	false)
		usb_remove_one 0 ;;
	help)
		help;;
	*)
		exit $NA ;;
esac
