#!/bin/sh
#
#    disable_crt_dvi: Disable CRT and DVI outputs.
#
#    Copyright (C) 2010 Canonical Ltd.
#
#    Authors: Andres Rodriguez <andreserl@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

video="/proc/acpi/ibm/video"

disable_crt_dvi() {
	if [ -w "$video" ]; then
		echo crt_$1 > $video
		echo dvi_$1 > $video
		echo lcf_$1 > $video
	fi
}

help() {
	echo "Disable CRT and DVI outputs."
}

case $1 in
	true)
		disable_crt_dvi disable ;;
	false)
		disable_crt_dvi enable ;;
	help)
		help;;
	*)
		exit $NA ;;
esac
